config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { in: 0..5 }
  # validates :rating, :inclusion => 1..10
  # validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    redirect_to restaurants_path(@restaurant)
    @restaurant.save
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # before_action :set_restaurant, only: %i[new create]

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="w-25 mx-auto mt-5">
<h1 class="my-4">All Restaurants</h1>
  <% @restaurants.each do |e| %>
  <h3> <%= link_to "#{e.name}", restaurant_path(e), class:"text-decoration-none" %> </h3>
  <% end %>
  <h4><%= link_to "+ Add new Restaurant", new_restaurant_path %> </h4>
</div>

app/views/restaurants/new.html.erb
<div class="container w-25 mt-5">
  <h2 class="container mt-5">Add a new Restaurant</h2>
    <di class=" container mt-2">
      <%= simple_form_for(@restaurant) do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :phone_number %>
        <%= f.input :category %>
        <%= f.submit %>
      <% end %>
      <%= link_to "go back", restaurants_path %>
    </div>
</div>

app/views/restaurants/show.html.erb
<div class="mx-auto w-25">
  <h2><%= @restaurant.name%></h2><br>
  <h2><%= @restaurant.address%></h2><br>
  <h2><%= @restaurant.phone_number%></h2><br>
  <h2><%= @restaurant.category%></h2><br>
  <%= link_to "go back", restaurants_path %>
</div>

<div class="w-25 mx-auto">
  <p><strong>Reviews:</strong></p>
<br><ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <div class="list-group-item" style="width:250px;"><%= review.content %></div>
    <div> <%= link_to "Delete",  review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure babe?"} %></div>
  <% end %>
</ul>
<br>

</div>
<div>
  <div style="width:150px; margin: 0 auto;"> <%= link_to "add a review",  new_restaurant_review_path(@restaurant), class:"btn mx-auto" %></div>
</div>

app/views/reviews/new.html.erb
<%# <h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p> %>
<div class="container w-25">
  <h1>New review</h1>
    <%= simple_form_for [@restaurant, @review] do |f| %>
      <%= f.input :content %>
      <%= f.input :rating %>
      <%= f.submit "Submit review", class: "btn btn-primary" %>
    <% end %>
</div>